### ISSUE TITLE
传参问题请教

### ISSUE THREAD

**Issue by xjia520** [laysent/silk-sdk#1]
您好！您的例子非常详细，感谢。有个地方不太明白，调用nodejs接口的时候，传递的参数是文件路径，但是接口内部貌似认为该参数是数据流，二者好像不太匹配？

比如解码的接口：
silk-sdk decode [input] [output]
where input is the name of **input file** and output is the name of **output file**. 
但Decode_Entry()内部调用Decode()时，传入的应该是buffer（我的理解是直接的数据，而非文件路径）：
return Decode(env, **buffer, bufferLength**, quiet ? 1 : 0, (float)loss_prob, API_Fs_Hz);

或者，在Decode_Entry()内部，这两部处理会对文件进行隐含的读取数据操纵吗？
status = napi_get_cb_info(env, info, &argc, args, NULL, NULL);
status = napi_get_buffer_info(env, args[0], &buffer, &bufferLength);
我的理解好像不会自动读取文件的数据，不知道哪里理解有误，望指教。

**Comment by laysent** [comment]
https://github.com/laysent/silk-sdk/blob/master/index.js#L39 我在 JavaScript 层做了一次转换，如果传入的是 string，会通过读取文件的方式转化成 Buffer，然后给底层的 API 调用

**Comment by xjia520** [comment]
> https://github.com/laysent/silk-sdk/blob/master/index.js#L39 我在 JavaScript 层做了一次转换，如果传入的是 string，会通过读取文件的方式转化成 Buffer，然后给底层的 API 调用
了解了，我原先没有仔细看index.js，谢谢！
